// THIS WILL BE WHERE I PUT SOME FUNCTIONS TO REPLACE SOME REPETITIVE CODE WHEN ADDING STAMPS AND CREATING FULL CARDS
// NEED TO PASS IN THE USER TO THESE FUNCTIONS
// PASS IN WHETHER THE REFERRER IS ADMIN OR USER SO THAT THE FUNCTION CAN CHOOSE DIFFERENT THINGS DEPENDING